apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: deploy-trigger-app
spec:
  selector:
    matchLabels:
      app: deploy-trigger
  template:
    metadata:
      labels:
        app: deploy-trigger
    spec:
      containers:
      - name: deploy-trigger-container
        image: scloudacr.azurecr.io/deploy-trigger-app:latest
