apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-agent
spec:
  replicas: 10 # Number of maximum nodes
  selector:
    matchLabels:
      app: log-app
  template:
    metadata:
      labels:
        app: log-app
    spec:
      affinity:
        podAntiAffinity:
          # requiredDuringSchedulingIgnoredDuringExecution:
          # - labelSelector:
          #     matchExpressions:
          #     - key: app
          #       operator: In
          #       values:
          #       - log-app
          #   topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - log-app
              topologyKey: kubernetes.io/hostname
      containers:
      - name: log-app-container
        image: scloudacr.azurecr.io/simple-app:latest
